# Generated by Django 5.0.7 on 2024-08-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profille', '0006_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
