# Generated by Django 5.1 on 2024-08-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profille', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
