# Generated by Django 5.1 on 2024-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profille', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('completed', 'Выполнен'), ('in_progress', 'В работе'), ('cancelled', 'Отменен')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
