# Generated by Django 5.0.4 on 2024-04-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('goal', models.TextField(verbose_name='Цель')),
                ('result', models.TextField(verbose_name='Результат')),
                ('xp_download_link', models.URLField(blank=True, verbose_name='Ссылка для загрузки XP')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео проекта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото проекта')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sownh.category', verbose_name='Категория')),
            ],
        ),
    ]
