# Generated by Django 5.0.4 on 2024-05-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sownh', '0003_categorytag_alter_categorynews_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='casecard',
            name='view_link',
        ),
    ]
