# Generated by Django 5.0.4 on 2024-05-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sownh', '0004_remove_casecard_image_remove_casecard_view_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casecard',
            options={'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterModelOptions(
            name='categorytag',
            options={'verbose_name': 'Категория-Кейс', 'verbose_name_plural': 'Категория-Кейсы'},
        ),
        migrations.AddField(
            model_name='casecard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='case_photos/', verbose_name='Фото'),
        ),
    ]
