# Generated by Django 5.0.7 on 2024-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sownh', '0005_alter_casecard_options_alter_categorytag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.IntegerField(max_length=12)),
            ],
        ),
    ]
