# Generated by Django 5.1 on 2024-08-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sownh', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
