# Generated by Django 5.1 on 2024-08-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sownh', '0007_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sownh.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Фотографии проекта',
            },
        ),
    ]
